/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostCodeRouteImport } from './routes/host.$code'
import { Route as RunCodeRouteImport } from './routes/run.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostCodeRoute = HostCodeRouteImport.update({
  id: '/host/$code',
  path: '/host/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RunCodeRoute = RunCodeRouteImport.update({
  id: '/run/$code',
  path: '/run/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host/$code': typeof HostCodeRoute
  '/run/$code': typeof RunCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host/$code': typeof HostCodeRoute
  '/run/$code': typeof RunCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host/$code': typeof HostCodeRoute
  '/run/$code': typeof RunCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/host/$code' | '/run/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/host/$code' | '/run/$code'
  id: '__root__' | '/' | '/host/$code' | '/run/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostCodeRoute: typeof HostCodeRoute
  RunCodeRoute: typeof RunCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$code': {
      id: '/host/$code'
      path: '/host/$code'
      fullPath: '/host/$code'
      preLoaderRoute: typeof HostCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$code': {
      id: '/run/$code'
      path: '/run/$code'
      fullPath: '/run/$code'
      preLoaderRoute: typeof RunCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostCodeRoute: HostCodeRoute,
  RunCodeRoute: RunCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
